name: 喜马拉雅极速版

on:
  schedule:
    - cron: '*/30 * * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          ${{ secrets.XMLY_HTTPS }}
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install requests
        
      - name: 'run 喜马拉雅极速版 1' 
        run: |
          cd ~/Scripts
          python3 xmly_speed.py
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须
            # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }} #非私密信息，去掉
            BARK: ${{ secrets.BARK }}     # bark服务
            SCKEY: ${{ secrets.SCKEY }}   # server酱服务
            TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
            TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id

      - name: 'run 喜马拉雅极速版 2'
        run: |
          cd ~/Scripts
          python3 xmly_speed.py
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_COOKIE_D }}
            
      - name: 'run 喜马拉雅极速版 3'
        run: |
          cd ~/Scripts
          python3 xmly_speed.py
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_COOKIE_WZ }}
