name: 喜马拉雅极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      XMLY_ZZ: true
      XMLY_DD: true
      XMLY_WZ: false
    steps:
      - name: Checkout
        run: |
          ${{ secrets.XMLY_HTTPS }}
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install requests
        
      - name: 'run 喜马拉雅极速版 ZZ'
        if: env.XMLY_ZZ == 'true'
        run: |
          cd ~/Scripts
          python3 xmly_speed_wuzhi01.py
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_COOKIE_Z }}  #必须
            # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }} #非私密信息，去掉
            BARK: ${{ secrets.BARK }}     # bark服务
            SCKEY: ${{ secrets.SCKEY }}   # server酱服务
            TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
            TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id

      - name: 'run 喜马拉雅极速版 DD'
        if: env.XMLY_DD == 'true'
        run: |
          cd ~/Scripts
          python3 xmly_speed_wuzhi01.py
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_COOKIE_D }}
            
      - name: 'run 喜马拉雅极速版 WZ'
        if: env.XMLY_WZ == 'true'
        run: |
          cd ~/Scripts
          python3 xmly_speed.py
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_COOKIE_WZ }}
