# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青安卓

on:
  workflow_dispatch:
  schedule:
     - cron: '*/22 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          ${{ secrets.ZQ_HTTPS }}
          
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      - name: npm install
        run: |
          cd ~/scripts
          npm install
          
      - name: '运行 【中青安卓】'
        run: |
          cd ~/scripts
          node Task/youthAndroid.js
       
